---

- name: Deploy web app
  hosts: "web"
  become: yes
  gather_facts: True

  vars:
    - project_path: "/opt/{{ project_name }}"
    - ansible_host_key_checking: false
  roles:
   - setup_docker_compose
   - copy_image
   - deploy_compose

